### ISSUE TITLE
Running PINet_new using only CPU?

### ISSUE THREAD

**Issue by oipa** [koyeongmin/PINet_new#19]
Hello all, 

I am trying to run CULane code just by using CPU (my machine does not have a dedicated GPU). I changed maplocation = torch.device('cpu') both in serialization.py (line 486) and agent.py (line 378). But I am getting the following error:

`(tdata2) C:\Users\...\PINet_new_cpu\CULane>python test.py`
`Testing`
`Get agent`
`model parameters:`
`4056849`
`Setup GPU mode`
`Testing loop`
`Traceback (most recent call last):
  File "test.py", line 382, in <module>
    Testing()
  File "test.py", line 96, in Testing
    _, _, ti = test(lane_agent, np.array([test_image]))
  File "test.py", line 277, in test
    result = lane_agent.predict_lanes_test(test_images)
  File "C:\Users\...\PINet_new_cpu\CULane\agent.py", line 346, in predict_lanes_test
    inputs = Variable(inputs).cuda()
  File "C:\Users\...\Anaconda3\envs\tdata2\lib\site-packages\torch\cuda\__init__.py", line 186, in _lazy_init
    _check_driver()
  File "C:\Users\...\Anaconda3\envs\tdata2\lib\site-packages\torch\cuda\__init__.py", line 61, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

Is possible to run this code without a dedicated GPU? If so, which are the changes I should do?

**Comment by oipa** [comment]
> Hello all,
> 
> I am trying to run CULane code just by using CPU (my machine does not have a dedicated GPU). I changed maplocation = torch.device('cpu') both in serialization.py (line 486) and agent.py (line 378). But I am getting the following error:
> 
> `(tdata2) C:\Users\...\PINet_new_cpu\CULane>python test.py`
> `Testing`
> `Get agent`
> `model parameters:`
> `4056849`
> `Setup GPU mode`
> `Testing loop`
> `Traceback (most recent call last): File "test.py", line 382, in <module> Testing() File "test.py", line 96, in Testing _, _, ti = test(lane_agent, np.array([test_image])) File "test.py", line 277, in test result = lane_agent.predict_lanes_test(test_images) File "C:\Users\...\PINet_new_cpu\CULane\agent.py", line 346, in predict_lanes_test inputs = Variable(inputs).cuda() File "C:\Users\...\Anaconda3\envs\tdata2\lib\site-packages\torch\cuda\__init__.py", line 186, in _lazy_init _check_driver() File "C:\Users\...\Anaconda3\envs\tdata2\lib\site-packages\torch\cuda\__init__.py", line 61, in _check_driver raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled`
> 
> Is possible to run this code without a dedicated GPU? If so, which are the changes I should do?

I solved my issue by:
 
- removing 65~68 lines in "test.py" (GPU check part)
- removing 299 line in "test.py" (torch.cuda.synchronize() )
- removing ".cuda()" from "agent.py" (some variables are passed to GPU by ".cuda")
- modifying load_weight in "agent.py" for map_location = 'cpu'

Thanks!
