### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by trra1988** [koyeongmin/PINet_new#47]
During the train process, also show this error:
Traceback (most recent call last):
  File "/home/lin/anaconda3/envs/PINet/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/lin/anaconda3/envs/PINet/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/lin/anaconda3/envs/PINet/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Does it matter? what this error for?

**Comment by NEFUtraffica** [comment]
I also encountered this problem during training, did you solve it, thank you
Traceback (most recent call last):
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Unable to connect due to aggressive rejection by the target computer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "F:\anaconda2022\envs\uvcgan\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "F:\anaconda2022\envs\uvcgan\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "F:\anaconda2022\envs\uvcgan\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "F:\anaconda2022\envs\uvcgan\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "F:\anaconda2022\envs\uvcgan\lib\http\client.py", line 951, in send
    self.connect()
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "F:\anaconda2022\envs\uvcgan\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000021EA7822B20>: Failed to establish a new connection: [WinError 10061] Unable to connect due to aggressive rejection by the target computer.

During handling of the above exception, another exception occurred:

**Comment by koyeongmin** [comment]
Hi! I am also trying to figure out the reason for this error. I think that "visdom" package is the problem because, only "visdom" package uses HTTP in this source code. I suggest removing the package if you don't need visualization for training loss. Thank you!

**Comment by NEFUtraffica** [comment]
Thank you for your answer, I will listen to your suggestions to make revisions, in addition, I would like to ask if the result of the tusimple dataset used in your paper is the highest ACC when testing, because I tried your code retraining, each round has a test result, can I pick the highest ACC as the result. Thank you very much for your help to me.

**Comment by NEFUtraffica** [comment]
> Hi! I am also trying to figure out the reason for this error. I think that "visdom" package is the problem because, only "visdom" package uses HTTP in this source code. I suggest removing the package if you don't need visualization for training loss. Thank you!

Thank you for your answer, I will listen to your suggestions to make revisions, in addition, I would like to ask if the result of the tusimple dataset used in your paper is the highest ACC when testing, because I tried your code retraining, each round has a test result, can I pick the highest ACC as the result. Thank you very much for your help to me.

**Comment by NEFUtraffica** [comment]
> Hi! I am also trying to figure out the reason for this error. I think that "visdom" package is the problem because, only "visdom" package uses HTTP in this source code. I suggest removing the package if you don't need visualization for training loss. Thank you!

Hello, I modified the model and retrained, I want to ask you whether the deval_result2_1_.txt output of each round of loop is the test set test result, and finally ask whether the post-processing is more time-consuming, do you have any optimization ideas
